config/routes.rb
Apollo::Application.routes.draw do
  resources :hospitals

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hospitals }
    end
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
    @hospital = Hospital.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hospital }
    end
  end

  # GET /hospitals/new
  # GET /hospitals/new.json
  def new
    @hospital = Hospital.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hospital }
    end
  end

  # GET /hospitals/1/edit
  def edit
    @hospital = Hospital.find(params[:id])
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(params[:hospital])

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render json: @hospital, status: :created, location: @hospital }
      else
        format.html { render action: "new" }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hospitals/1
  # PUT /hospitals/1.json
  def update
    @hospital = Hospital.find(params[:id])

    respond_to do |format|
      if @hospital.update_attributes(params[:hospital])
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy

    respond_to do |format|
      format.html { redirect_to hospitals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% @hospital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<h1>Listing hospitals</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hospitals.each do |hospital| %>
  <tr>
    <td><%= hospital.name %></td>
    <td><%= link_to 'Show', hospital %></td>
    <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
    <td><%= link_to 'Destroy', hospital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hospital.name %>
</p>


<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apollo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>